SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `tutoring_website`;
CREATE SCHEMA IF NOT EXISTS `tutoring_website` DEFAULT CHARACTER SET utf8 ;
USE `tutoring_website` ;

-- -----------------------------------------------------
-- Table `tutoring_website`.`User_Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutoring_website`.`User_Login` (
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Contact` VARCHAR(10) NULL,
  `Gender` VARCHAR(45) NULL,
  `DateOfBirth` VARCHAR(45) NULL,
  `Passwords` VARCHAR(45) NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;

INSERT INTO User_Login (FirstName, LastName, Email, Contact, Gender, DateOfBirth, Passwords)
VALUES 
('Adam', 'Erichsen', 'adameric123@gmail.com', '0716523447', 'Male', '1975-06-11', '2458874'),
('Andrew', 'Hart', 'hart.andrew117@gmail.com', '0712801913', 'Male', '1999-11-11', '123456'),
('David', 'Beckham', 'beckham9@gmail.com', '0832546995', 'Male', '1985-07-01', '4758454'),
('Bryan', 'Garcia', 'garciabryan@gmail.co.za', '0619923412', 'Male', '1995-04-17', '547874'),
('Buddy', 'Johnson', 'buddy777@gmail.com', '0746598211', 'Male', '1969-08-22', '2447175'),
('Casey', 'Martin', 'martins@gmail.com', '0846571121', 'Female', '1988-02-11', '63598989'),
('Chen', 'Tsuniu', 'chenman@gmail.com', '0654872321', 'Male', '1987-12-04', '452124547'),
('Chevonne', 'Stanley', 'stangirl@gmail.com', '0684755122', 'Female', '1991-10-27', '32145251'),
('Chinli', 'Muchitu', 'muchiti3@gmail.com', '0625415882', 'Male', '1984-06-24', '0215477'),
('Cooper', 'Daniels', 'coopbuck@gmail.co.za', '087413447', 'Male', '1944-05-11', '13778874'),
('Cristiano', 'Ronaldo', 'cr7@gmail.com', '0856325412', 'Male', '1994-02-09', '4578411'),
('Gerald', 'Pique', 'barca@gmail.com', '0741225547', 'Male', '1986-01-11', '24871166'),
('Steven', 'Giroud', 'gerryfrance@gmail.com', '0796325412', 'Male', '1999-08-12', '123456874'),
('Jana', 'Lee', 'leejana@gmail.com', '0721452334', 'Female', '1992-12-11', '13654874'),
('Jennifer', 'Arniston', 'friends@gmail.com', '0774655221', 'Femail', '1982-09-23', '147755474'),
('Joshua', 'Mccoy', 'josh767@gmail.com', '0755655147', 'Male', '1975-05-11', '2458874'),
('Lionel', 'Messi', 'messi10@gmail.com', '0865213447', 'Male', '1980-07-09', '10101010'),
('Lisa', 'Kapisa', 'kappielisa@gmail.com', '088464647', 'Female', '2001-02-28', '14758269'),
('Lize', 'De Jong', 'lizedejong@gmail.com', '0754136812', 'Female', '1998-11-04', '124754848'),
('Megan', 'Pienaar', 'megzbanana@gmail.com', '0877734147', 'Female', '1997-12-12', '13467958462'),
('Michael', 'Jordan', 'jordimike@gmail.com', '0716154871', 'Male', '1996-03-08', '12149632474'),
('Mila', 'Botha', 'botham3@gmail.com', '0823654781', 'Female', '1987-11-09', '1156784005'),
('Nadia', 'Louw', 'lowkeynadz@gmail.com', '0745487871', 'Female', '1978-07-12', '012454871'),
('Neymar', 'Junior', 'neymar123@gmail.com', '0811020047', 'Male', '1986-01-05', '138105674'),
('Nicole', 'Jenkins', 'jenkyjam@gmail.com', '0714569855', 'Female', '1997-11-13', '2124851274');


-- -----------------------------------------------------
-- Table `tutoring_website`.`Tutor_Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutoring_website`.`Tutor_Post` (
  `idtutor` INT NOT NULL AUTO_INCREMENT,
  `User_Email` VARCHAR(100) NOT NULL,
  `Subjects` VARCHAR(45) NULL,
  `Suburb` VARCHAR(45) NULL,
  `TutoringExperience` VARCHAR(45) NULL,
  `Qualification` VARCHAR(100) NULL,
  `PlaceOfEducation` VARCHAR(45) NULL,
  `YearComplete` INT(4) NULL,
  `OwnTransport` VARCHAR(5) NULL,
  `LessonPrice` INT NULL,
  `Descriptions` VARCHAR(500) NULL,
  `Ageranges` VARCHAR(45) NULL,
  `DrivingRadius` INT(10) NULL,
  `Images` VARCHAR(100) NULL,
  PRIMARY KEY (`idtutor`),
  INDEX `fk_tutor_User_idx` (`User_Email` ASC),
  CONSTRAINT `fk_tutor_User`
    FOREIGN KEY (`User_Email`)
    REFERENCES `tutoring_website`.`User_Login` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO Tutor_Post (User_Email, Subjects, Suburb, TutoringExperience, Qualification, PlaceOfEducation, YearComplete, OwnTransport, LessonPrice, Descriptions, Ageranges, DrivingRadius, Images)
VALUES 
('adameric123@gmail.com', 'Information Technology', 'Ashton', 'none', 'none', 'Stellenbosch', 2020, 'No', 120, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '0 - 3', 20, 'adam.jpg'),
('hart.andrew117@gmail.com', 'Mathematics', 'Bellville', 'none', 'none', 'Stellenbosch', 2020, 'No', 145, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.',  '0 - 3', 30, 'andrew.jpg'),
('beckham9@gmail.com', 'Business', 'Blouberg', '0 to 1 years', 'none', 'Stellenbosch', 2019, 'Yes', 120, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.',  '20 +', 40, 'beckham.jpg'),
('beckham9@gmail.com', 'Information Technology', 'Blouberg', '0 to 1 years', 'Bachelors Degree', 'Stellenbosch', 2018, 'Yes', 95, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.',  '20 +', 40, 'beckham.jpg'),
('garciabryan@gmail.co.za', 'Afrikaans', 'Paarl', 'none', 'Bachelors Degree', 'Stellenbosch', 2018, 'Yes', 65, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '4 - 7', 50, 'bryan.jpg'),
('buddy777@gmail.com', 'Mathematics', 'Ashton', '0 to 1 years', 'Bachelors Degree', 'Stellenbosch', 2017, 'Yes', 78, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '4 - 7', 30, 'buddy.jpg'),
('buddy777@gmail.com', 'English',  'Ashton', '0 to 1 years', 'Bachelors Degree', 'Stellenbosch', 2020, 'Yes', 130, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '20 +', 20, 'buddy.jpg'),
('buddy777@gmail.com', 'Physics', 'Ashton', '0 to 1 years', 'Honours Degree', 'Stellenbosch', 2018, 'Yes', 178, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '20 +', 30, 'buddy.jpg'),
('buddy777@gmail.com', 'Afrikaans', 'Ashton', '0 to 1 years', 'Honours Degree', 'Stellenbosch', 2012, 'Yes', 192, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '4 - 7', 30, 'buddy.jpg'),
('martins@gmail.com', 'Information Technology', 'Stellenbosch', '0 to 1 years', 'Honours Degree', 'Stellenbosch', 2014, 'Yes', 156, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '8 - 11', 30, 'casey.jpg'),
('chenman@gmail.com', 'Mathematics', 'Constantia', '0 to 1 years','Honours Degree', 'CPUT', 2015, 'Yes', 123, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '8 - 11', 40, 'chen.jpg'),
('stangirl@gmail.com', 'Mathematics', 'Durbanville', '3 + years', 'CFP', 'CPUT', 2016, 'Yes', 140, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '8 - 11', 40, 'chevonne.jpg'),
('stangirl@gmail.com', 'Physics', 'Durbanville', '3 + years', 'CFP', 'CPUT', 2018, 'Yes', 180, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '20 +', 40, 'chevonne.jpg'),
('stangirl@gmail.com', 'Business', 'Durbanville', '3 + years', 'CFP', 'CPUT', 2013, 'Yes', 200, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '8 - 11', 50, 'chevonne.jpg'),
('muchiti3@gmail.com', 'Information Technology', 'Swellendam', '1 to 3 years', 'CFP', 'CPUT', 2017, 'Yes', 200, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '8 - 11', 20, 'chinli.jpg'),
('coopbuck@gmail.co.za', 'English', 'Table View', '1 to 3 years', 'Masters Degree', 'UCT', 2018, 'Yes', 123, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '8 - 11', 10, 'chris.jpg'),
('cr7@gmail.com', 'Biology', 'Robertson', '1 to 3 years', 'Masters Degree', 'UCT', 2019, 'Yes', 128, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '8 - 11', 0, 'cristiano.jpg'),
('barca@gmail.com', 'Afrikaans', 'Worcester', '0 to 1 years', 'Masters Degree', 'UCT', 2017, 'Yes', 55, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.','8 - 11', 30, 'gerald.jpg'),
('barca@gmail.com', 'Mathematics', 'Worcester', '0 to 1 years', 'Masters Degree', 'UCT', 2016, 'Yes', 62, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 10, 'gerald.jpg'),
('gerryfrance@gmail.com', 'Accounting', 'Bellville', '1 to 3 years', 'National Certificate', 'UCT', 2016, 'Yes', 56, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 20, 'giroud.jpg'),
('leejana@gmail.com', 'Information Technology', 'Blouberg', '1 to 3 years', 'National Certificate', 'UCT', 2017, 'Yes', 43, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 10, 'jana.jpg'),
('friends@gmail.com', 'Business', 'Ladysmith', '0 to 1 years', 'National Certificate', 'UCT', 2016, 'Yes', 88, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 15, 'jennifer.jpg'),
('friends@gmail.com', 'Accounting', 'Ladysmith', '0 to 1 years', 'National Certificate', 'UCT', 2019, 'Yes', 120, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 20, 'jennifer.jpg'),
('josh767@gmail.com', 'Mathematics', 'Ladysmith', '1 to 3 years', 'Technikon Diploma', 'UCT', 2020, 'No', 180, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 40, 'joshua.jpg'),
('messi10@gmail.com', 'Accounting', 'Brackenfell', 'none', 'Technikon Diploma', 'UCT', 2016, 'No', 145, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 30, 'lionel.jpg'),
('messi10@gmail.com', 'English', 'Brackenfell', 'none', 'Technikon Diploma', 'UCT', 2016, 'No', 134, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 20, 'lionel.jpg'),
('messi10@gmail.com', 'Physics', 'Brackenfell', 'none', 'Technikon Diploma', 'UCT', 2010, 'No', 166, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 40, 'lionel.jpg'),
('kappielisa@gmail.com', 'Information Technology', 'Kraaifontein', '3 + years', 'B-Tech Degree', 'UCT', 2016, 'No', 170, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 15, 'lisa.jpg'),
('kappielisa@gmail.com', 'Biology', 'Kraaifontein', '3 + years', 'B-Tech Degree', 'UCT', 2010, 'No', 120, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 30, 'lisa.jpg'),
('lizedejong@gmail.com', 'Afrikaans', 'Durbanville', '0 to 1 years', 'B-Tech Degree', 'Pearson', 2015, 'No', 90, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '12 - 15', 15, 'lize.jpg'),
('megzbanana@gmail.com', 'English', 'Ceres', '1 to 3 years', 'B-Tech Degree', 'Pearson', 2012, 'No', 88, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '16 - 19', 12, 'megan.jpg'),
('jordimike@gmail.com', 'Biology', 'Ashton', '0 to 1 years', 'M-Tech Degree', 'Pearson', 2017, 'No', 78, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '16 - 19', 45, 'michael.jpg'),
('botham3@gmail.com', 'Business', 'George', 'none', 'M-Tech Degree', 'Pearson', 2016, 'No', 50, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '16 - 19', 24, 'mila.jpg'),
('botham3@gmail.com', 'Accounting', 'George', 'none', 'M-Tech Degree', 'Pearson', 2016, 'No', 60, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '16 - 19', 12, 'mila.jpg'),
('botham3@gmail.com', 'Afrikaans', 'George', 'none', 'M-Tech Degree', 'Pearson', 2016, 'No', 45, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '16 - 19', 23, 'mila.jpg'),
('lowkeynadz@gmail.com', 'Mathematics', 'Brackenfell', '1 to 3 years', 'Diploma', 'Pearson', 2020, 'No', 67, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '16 - 19', 45, 'nadia.jpg'),
('neymar123@gmail.com', 'Biology', 'Cape Town', 'none', 'Diploma', 'Pearson', 2019, 'No', 45, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '16 - 19', 60, 'neymar.jpg'),
('neymar123@gmail.com', 'English', 'Cape Town', 'none', 'Diploma', 'Pearson', 2018, 'No', 89, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '16 - 19', 25, 'neymar.jpg'),
('neymar123@gmail.com', 'Information Technology', 'Cape Town', 'none', 'Matric', 'UWC', 2017, 'No', 100, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '16 - 19', 45, 'neymar.jpg'),
('jenkyjam@gmail.com', 'Mathematics', 'Bellville', '1 to 3 years', 'Matric', 'UWC', 2016, 'No', 105, 'I enjoy teaching this subject for one of two reasons. Firstly I am very familiar with this specific subject and feel that teaching it to other people will be no issue. Secondly, I enjoy public speaking, which means that I have no problem with teaching your child. I am a very comfortable speaker and have lots of patience. I love answering questions and I feel like I am the solution to your childs struggle. Please contact me if you want any more information regarding the lessons.', '16 - 19', 60, 'nicole.jpg');




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
